// <auto-generated />
using System;
using Infra.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527145310_Insert")]
    partial class Insert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DhTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DH_TIMESTAMP")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("ACCESS_LEVEL", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DhTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DH_TIMESTAMP")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDiscount")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DISCOUNT");

                    b.Property<int>("IdGame")
                        .HasColumnType("INT")
                        .HasColumnName("ID_GAME");

                    b.Property<float>("PercentOff")
                        .HasColumnType("real")
                        .HasColumnName("PERCENT_OFF");

                    b.Property<DateTime>("StartDiscount")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DISCOUNT");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdGame")
                        .HasDatabaseName("IX_Discount_IdGame");

                    b.ToTable("DISCOUNT", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("ABOUT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEVELOPER");

                    b.Property<DateTime>("DhTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DH_TIMESTAMP")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GENRE");

                    b.Property<decimal>("Metacritic")
                        .HasColumnType("DECIMAL(3,1)")
                        .HasColumnName("METACRITIC");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PUBLISHER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RELEASE_DATE");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("Genre")
                        .HasDatabaseName("IX_Game_Genre");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Game_Title");

                    b.ToTable("GAME", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DhTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DH_TIMESTAMP")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("IdAccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID_ACCESS_LEVEL")
                        .HasDefaultValueSql("2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("PASSWORD");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("IdAccessLevel")
                        .HasDatabaseName("IX_User_IdAccessLevel");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DhTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DH_TIMESTAMP")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdGame")
                        .HasColumnType("INT")
                        .HasColumnName("ID_GAME");

                    b.Property<int>("IdUser")
                        .HasColumnType("INT")
                        .HasColumnName("ID_USER");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdGame")
                        .HasDatabaseName("IX_UserGame_IdGame");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_UserGame_IdUser");

                    b.ToTable("USER_GAME", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Discount", b =>
                {
                    b.HasOne("Domain.Entity.Game", "Game")
                        .WithMany("Discounts")
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.HasOne("Domain.Entity.AccessLevel", "AccessLevel")
                        .WithMany("User")
                        .HasForeignKey("IdAccessLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("Domain.Entity.UserGame", b =>
                {
                    b.HasOne("Domain.Entity.Game", "Game")
                        .WithMany("UserGame")
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User", "User")
                        .WithMany("UserGame")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.AccessLevel", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Game", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("UserGame");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Navigation("UserGame");
                });
#pragma warning restore 612, 618
        }
    }
}
