@App_HostAddress = http://localhost:5238


GET {{App_HostAddress}}/api/Games/saveGame
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBjbG91ZGdhbWVzLmNvbS5iciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiI2NmFhZWMwYi1hYTExLTRhOGItYjQyNi05MjYzODE3NmQ3NWIiLCJleHAiOjE3NDg3OTYwMDgsImlzcyI6ImZpYXAiLCJhdWQiOiJjbG91ZC1nYW1lcyJ9.5iU6ROWJ_DJhA7b_uagAIUGhoELjuXXz2uMjZ9gKDHA

###

GET {{App_HostAddress}}/api/Games/getGames
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBjbG91ZGdhbWVzLmNvbS5iciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiI2NmFhZWMwYi1hYTExLTRhOGItYjQyNi05MjYzODE3NmQ3NWIiLCJleHAiOjE3NDg3OTYwMDgsImlzcyI6ImZpYXAiLCJhdWQiOiJjbG91ZC1nYW1lcyJ9.5iU6ROWJ_DJhA7b_uagAIUGhoELjuXXz2uMjZ9gKDHA